### ISSUE TITLE
duplicate project

### ISSUE THREAD

**Issue by EliasSalom** [Fullstack-Alfanar/yosef-a-resume#2]
this project has been duplicated and used before please, send me the source

**Comment by yosef406** [comment]
this project was inspired by the following website http://www.pascalvangemert.nl/#/profile .
some of the elements that were taken are the stars icons 
other inspirations were taken from youtube: https://www.youtube.com/watch?v=GUEB9FogoP8&t=661s
some elements were taken from bootstrap:  https://getbootstrap.com/docs/5.1/examples/headers/ (the first header)
other bootstrap elements: 
https://getbootstrap.com/docs/5.1/layout/gutters/#row-columns-gutters

**Comment by EliasSalom** [comment]
check this 
![Screenshot from 2022-03-24 03-11-44](https://user-images.githubusercontent.com/39850311/159822913-73ba7597-a666-42d0-9e72-100b0a9f9ca5.png)
